module.exports = {
  fakeResults: {
    "Response":
    {
      "Meta":
      {
        "ExecutionTime": "1431570399.2744"
      },
      "Data":
      {
        "Entities":
        {
          "Entity":
          [
            {
              "id": "106423",
              "name": "Walmart Stores U.S",
              "description": "Largest division of Walmart Stores, Inc.",
              "summary": "",
              "start_date": "",
              "end_date": "",
              "website": "",
              "is_current": "",
              "primary_type": "Org",
              "parent_id": "1",
              "updated_at": "2013-09-29 12:31:14",
              "uri": "http://littlesis.org/org/106423/Walmart_Stores_U.S",
              "api_uri": "http://api.littlesis.org/entity/106423.xml"
            },
            {
              "id": "1",
              "name": "Walmart",
              "description": "Retail merchandising",
              "summary": "",
              "start_date": "",
              "end_date": "",
              "website": "http://www.walmartstores.com",
              "is_current": "1",
              "primary_type": "Org",
              "parent_id": "",
              "updated_at": "2015-04-15 20:32:23",
              "uri": "http://littlesis.org/org/1/Walmart",
              "api_uri": "http://api.littlesis.org/entity/1.xml"
            },
            {
              "id": "77304",
              "name": "The Walmart Foundation",
              "description": "Wal-Mart foundation",
              "summary": "",
              "start_date": "",
              "end_date": "",
              "website": "",
              "is_current": "",
              "primary_type": "Org",
              "parent_id": "",
              "updated_at": "2014-10-13 18:23:14",
              "uri": "http://littlesis.org/org/77304/The_Walmart_Foundation",
              "api_uri": "http://api.littlesis.org/entity/77304.xml"
            },
            {
              "id": "1016",
              "name": "Michael T Duke",
              "description": "President and CEO of Walmart",
              "summary": "Mike Duke is the president and chief executive officer of Wal-Mart Stores, Inc. (Walmart). From 2005 to February 2009, Mike served as vice chairman of the company, with responsibility for Walmart International.",
              "start_date": "1949-12-07",
              "end_date": "",
              "website": "",
              "is_current": "1",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2014-07-24 15:45:35",
              "uri": "http://littlesis.org/person/1016/Michael_T_Duke",
              "api_uri": "http://api.littlesis.org/entity/1016.xml"
            },
            {
              "id": "92138",
              "name": "Ed Chan",
              "description": "President, CEO - Walmart China",
              "summary": "Ed Chan joined Walmart in 2006 & become President and CEO of Walmart China in February 2007. He is responsible for the companyâs China retail operation and chair the global Zero Waste efforts in the company.",
              "start_date": "",
              "end_date": "",
              "website": "",
              "is_current": "",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2014-02-17 10:30:02",
              "uri": "http://littlesis.org/person/92138/Ed_Chan",
              "api_uri": "http://api.littlesis.org/entity/92138.xml"
            },
            {
              "id": "33550",
              "name": "Sylvia Mathews Burwell",
              "description": "Secretary, Health and Human Services | former president of the Walmart Foundation",
              "summary": "Sylvia Mathews Burwell is president of the Walmart Foundation, where she leads the company's charitable giving efforts and Walmart's Global Women's Economic Empowerment Initiative. Ms. Burwell also guides the company's social, environmental, and economic opportunity efforts in Africa. Prior to joining Walmart, Ms. Burwell was president of the global development program at the Bill and Melinda Gates Foundation, where she led a variety of initiatives including grantmaking and advocacy in agricultural development; financial services for the poor; and water, sanitation, and hygiene. Before joining the Bill and Melinda Gates foundation, Ms. Burwell served in the Clinton administration as deputy director of the Office of Management and Budget, deputy chief of staff to the president, and chief of staff to Secretary of the Treasury Robert E. Rubin. She is based in Bentonville, AR.",
              "start_date": "1965-00-00",
              "end_date": "",
              "website": "",
              "is_current": "",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2015-03-26 23:29:24",
              "uri": "http://littlesis.org/person/33550/Sylvia_Mathews_Burwell",
              "api_uri": "http://api.littlesis.org/entity/33550.xml"
            },
            {
              "id": "43964",
              "name": "Raul Vazquez",
              "description": "CEO, Walmart.com",
              "summary": "As President and CEO of Walmart.com, Raul Vazquez oversees the online development and operations of the worldâs largest retailer. He was promoted to this position in early 2007.",
              "start_date": "",
              "end_date": "",
              "website": "",
              "is_current": "1",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2012-02-23 16:48:19",
              "uri": "http://littlesis.org/person/43964/Raul_Vazquez",
              "api_uri": "http://api.littlesis.org/entity/43964.xml"
            },
            {
              "id": "96401",
              "name": "Mitchell Goldhar",
              "description": "Canadian real estate billionaire",
              "summary": "Legend has it in his native Toronto that SmartCentres President and CEO Mitchell Goldhar paid an unsolicited visit to Sam Walton in the early 1990s, refusing to leave the prolific retailer's Arkansas office until the older man agreed to name Goldhar his exclusive developer in Canada. Though Walton declined, Goldhar's tenacity had impressed Walton enough to give him a shot. The rest is history as Goldhar soon became Walmart's de facto exclusive developer in the country, literally paving the way for Walmart as it moved into the market. Goldhar is still developing his Walmart-anchored SmartCentres, many of which he then sells to Calloway, a real estate investment trust in which he holds a 22% stake. He manages the parallel operations out of SmartCentres headquarters, known as 'the Igloo,' in Vaughn, Ontario.",
              "start_date": "",
              "end_date": "",
              "website": "",
              "is_current": "",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2015-03-09 16:47:47",
              "uri": "http://littlesis.org/person/96401/Mitchell_Goldhar",
              "api_uri": "http://api.littlesis.org/entity/96401.xml"
            },
            {
              "id": "184430",
              "name": "Stephanie Yazgi",
              "description": "Political Operative",
              "summary": "Stephanie Yazgi is an experienced community organizer, political strategist, and coalition-builder with a track record of winning issue and electoral campaigns. At her previous job with the Center for Popular Democracy, she focused on capacity building, campaign development, and strategic organizing initiatives on a variety of issues. She uses her experience in the field and to craft trainings and curricula for use by campaigns and membership based organizations across the country. Before that, she was the Campaign Director for Walmart Free NYC, a groundbreaking campaign, part of the UFCW International Unionâs Making Change at Walmart network, that defeated Walmartâs multi-million dollar effort to enter New York City. Prior to that, Stephanie worked as a senior operative for the New York State Senate Democratic Conference managing a statewide operation to promote progressive legislation through issue organizing campaigns and constituency mobilization. Through her work with the NYS-DSCC, she managed electoral campaigns, with a focus in strong field operations, to elect Democrats to that house which tipped the balance of power in their favor for the first time in 43 years. She attended Boston University where she majored in Sociology, then went on to Columbia University School of Social work where she obtained her M.S.S.W. Over the years, she has authored and facilitated a number of trainings on community, political and electoral organizing and is an adjunct professor of social work at Hunter College and NYU.",
              "start_date": "",
              "end_date": "",
              "website": "",
              "is_current": "",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2015-02-22 16:56:23",
              "uri": "http://littlesis.org/person/184430/Stephanie_Yazgi",
              "api_uri": "http://api.littlesis.org/entity/184430.xml"
            },
            {
              "id": "67826",
              "name": "Jesse H Ruiz",
              "description": "Partner, Drinker Biddle & Reath",
              "summary": "Jesse H. Ruiz is a partner in the firm's Corporate and Securities Group, serves as the firm's Marketing Partner, and is a member of the firmâs Client Service Committee.  For over 16 years, Jesse has focused his practice on business transactions, including mergers and acquisitions, venture capital and private equity investments, equity and debt offerings, financings, the purchase and sale of assets from bankruptcy estates and a variety of commercial transactions.  Drawing on his experiences in business and management consulting, and his work in the public sector, Jesse also counsels public and privately-held companies and entrepreneurs on strategic initiatives and transactions.  Jesse also counsels clients on corporate finance issues; negotiation of consulting and other commercial agreements; reorganizations; corporate compliance; corporate governance issues; employment matters; and the formation of business entities in the United States, Latin America and Europe.",
              "start_date": "",
              "end_date": "",
              "website": "",
              "is_current": "",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2014-11-28 00:23:26",
              "uri": "http://littlesis.org/person/67826/Jesse_H_Ruiz",
              "api_uri": "http://api.littlesis.org/entity/67826.xml"
            },
            {
              "id": "94382",
              "name": "Michael S Moore",
              "description": "President, Walmart Central, Walmart U.S.",
              "summary": "",
              "start_date": "",
              "end_date": "",
              "website": "",
              "is_current": "",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2014-05-09 22:29:02",
              "uri": "http://littlesis.org/person/94382/Michael_S_Moore",
              "api_uri": "http://api.littlesis.org/entity/94382.xml"
            },
            {
              "id": "153482",
              "name": "Michael J Bender",
              "description": "President, Walmart West, Walmart U.S.",
              "summary": "",
              "start_date": "",
              "end_date": "",
              "website": "",
              "is_current": "",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2014-05-09 22:31:02",
              "uri": "http://littlesis.org/person/153482/Michael_J_Bender",
              "api_uri": "http://api.littlesis.org/entity/153482.xml"
            },
            {
              "id": "153487",
              "name": "Pamela K Kohn",
              "description": "Executive Vice President and President, Walmart Realty, Walmart U.S.",
              "summary": "",
              "start_date": "",
              "end_date": "",
              "website": "",
              "is_current": "",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2014-05-09 22:33:01",
              "uri": "http://littlesis.org/person/153487/Pamela_K_Kohn",
              "api_uri": "http://api.littlesis.org/entity/153487.xml"
            },
            {
              "id": "153494",
              "name": "JoaquÃ­n GonzÃ¡lez Varela",
              "description": "President, Walmart East, Walmart U.S.",
              "summary": "",
              "start_date": "",
              "end_date": "",
              "website": "",
              "is_current": "",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2014-05-09 22:19:13",
              "uri": "http://littlesis.org/person/153494/JoaquÃ­n_GonzÃ¡lez_Varela",
              "api_uri": "http://api.littlesis.org/entity/153494.xml"
            },
            {
              "id": "1009",
              "name": "Gregory Boyd Penner",
              "description": "General Partner at Madrone Capital Partners; grandson-in-law of Sam Walton",
              "summary": "Mr. Penner has been a General Partner at Madrone Capital Partners, an investment management firm, since 2005. From 2002 to 2005, he served as Wal-Mart's Senior Vice President and Chief Financial Officer - Japan. Prior to working for Wal-Mart, Mr. Penner was a General Partner at Peninsula Capital, an early stage venture capital fund, and a financial analyst for Goldman, Sachs & Co. Mr. Penner is a member of the board of directors of Baidu.com, Inc., 99Bill Corporation, Cuill Inc., and Global Hyatt Corporation.",
              "start_date": "1970-00-00",
              "end_date": "",
              "website": "",
              "is_current": "",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2014-06-07 15:36:12",
              "uri": "http://littlesis.org/person/1009/Gregory_Boyd_Penner",
              "api_uri": "http://api.littlesis.org/entity/1009.xml"
            },
            {
              "id": "2554",
              "name": "Jeanne P Jackson",
              "description": "",
              "summary": "Jeanne P. Jackson Ms. Jackson is the General Partner of MSP Capital, a consulting and investment firm she founded in 2003. Ms. Jackson was Chief Executive Officer of Walmart. com from March 2000 to January 2002. Ms. Jackson joined McDonald's Board in 1999 and is a member of the class of 2009. She also serves on the boards of NIKE, Inc. and Nordstrom, Inc.",
              "start_date": "1952-00-00",
              "end_date": "",
              "website": "",
              "is_current": "",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2013-11-18 14:44:59",
              "uri": "http://littlesis.org/person/2554/Jeanne_P_Jackson",
              "api_uri": "http://api.littlesis.org/entity/2554.xml"
            },
            {
              "id": "3205",
              "name": "Margaret A McKenna",
              "description": "Former President, Walmart Foundation",
              "summary": "MARGARET A. McKENNA president, The Wal-Mart Foundation and former president, Lesley University. She received her undergraduate degree from Emmanuel College and her law degree from Southern Methodist University. Ms. McKenna was a civil rights attorney with the U.S. Department of Justice and held a variety of positions with the U.S. government from 1976 to 1981, including deputy counsel in the White House and deputy under secretary of education.",
              "start_date": "1946-00-00",
              "end_date": "",
              "website": "",
              "is_current": "",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2015-03-27 00:18:55",
              "uri": "http://littlesis.org/person/3205/Margaret_A_McKenna",
              "api_uri": "http://api.littlesis.org/entity/3205.xml"
            },
            {
              "id": "6063",
              "name": "Rosalind G Brewer",
              "description": "SVP, Division President - Walmart",
              "summary": "Director of Molson Coors since February 2006. Ms. Brewer has been Senior Vice President and Division President of Operations and Regional General Manager of Wal-Mart Stores, Inc. since 2006. From 2004 to 2006, she served as President of Global Nonwovens division of Kimberly-Clark Corporation. Ms. Brewer had been with Kimberly-Clark since 1984, and held a variety of leadership positions across multiple businesses spanning technology and business aspects of the company. Ms. Brewer is immediate past president of Georgia's non-profit Board of Directors Network, and serves on several other non-profit boards. She holds a B.S. in Chemistry from Spelman College, and has been a trustee of Spelman College since 2006.",
              "start_date": "1963-00-00",
              "end_date": "",
              "website": "",
              "is_current": "",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2014-09-25 00:29:20",
              "uri": "http://littlesis.org/person/6063/Rosalind_G_Brewer",
              "api_uri": "http://api.littlesis.org/entity/6063.xml"
            },
            {
              "id": "33448",
              "name": "Ann Walker Marchant",
              "description": "D.C. socialite and niece of Vernon Jordan",
              "summary": "Ann Walker Marchant is the founder and CEO of the Walker Marchant Group (WMG) - a public relations firm specializing in corporate communications, litigation communications, issues management and media planning. With a core client base across industry lines, WMG provides strategic and targeted solutions to corporate brand challenges.",
              "start_date": "",
              "end_date": "",
              "website": "",
              "is_current": "",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2014-06-21 17:52:41",
              "uri": "http://littlesis.org/person/33448/Ann_Walker_Marchant",
              "api_uri": "http://api.littlesis.org/entity/33448.xml"
            },
            {
              "id": "35771",
              "name": "Donald S Perkins",
              "description": "Retired Chairman, Jewel Companies, Inc.",
              "summary": "Donald Perkins, a retired grocery executive and the first chairman of the Civic Committee of the Commercial Club of Chicago, died March 25 2015 at his Northfield home, according to Smith-Corcoran Funeral Home. He was 88.",
              "start_date": "1927-00-00",
              "end_date": "2015-03-25",
              "website": "",
              "is_current": "",
              "primary_type": "Person",
              "parent_id": "",
              "updated_at": "2015-03-28 15:22:16",
              "uri": "http://littlesis.org/person/35771/Donald_S_Perkins",
              "api_uri": "http://api.littlesis.org/entity/35771.xml"
            }
          ]
        }
      }
    }
  }
};
