module.exports = {
  searchEntitiesResult: [
  { id: '106423',
    name: 'Walmart Stores U.S',
    description: 'Largest division of Walmart Stores, Inc.',
    summary: '',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Org',
    parent_id: '1',
    updated_at: '2013-09-29 12:31:14',
    uri: 'http://littlesis.org/org/106423/Walmart_Stores_U.S',
    api_uri: 'http://api.littlesis.org/entity/106423.xml' },
  { id: '1',
    name: 'Walmart',
    description: 'Retail merchandising',
    summary: '',
    start_date: '',
    end_date: '',
    website: 'http://www.walmartstores.com',
    is_current: '1',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2015-06-15 12:22:47',
    uri: 'http://littlesis.org/org/1/Walmart',
    api_uri: 'http://api.littlesis.org/entity/1.xml' },
  { id: '77304',
    name: 'The Walmart Foundation',
    description: 'Wal-Mart foundation',
    summary: '',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2014-10-13 18:23:14',
    uri: 'http://littlesis.org/org/77304/The_Walmart_Foundation',
    api_uri: 'http://api.littlesis.org/entity/77304.xml' },
  { id: '1016',
    name: 'Michael T Duke',
    description: 'President and CEO of Walmart',
    summary: 'Mike Duke is the president and chief executive officer of Wal-Mart Stores, Inc. (Walmart). From 2005 to February 2009, Mike served as vice chairman of the company, with responsibility for Walmart International.\r\n\r\nAs CEO, Mike leads a strong management team that is focused on keeping Walmartâs mission of âsaving people money so they can live betterâ relevant to every customer, every day. The company also continues to broaden and accelerate its global efforts on environmental sustainability, responsible sourcing and associate opportunity.\r\n\r\nSince joining Walmart in 1995, Mike has led the logistics, distribution and administration divisions as well as Walmart U.S. As vice chairman, Mike was actively involved in developing and executing corporate strategy. He focused on setting higher standards of excellence for the companyâs resources and people â from the redesign of logistics and merchandise distribution systems, to the recruitment of talent, and development of strong teams.\r\n\r\nUnder Mikeâs leadership, the companyâs international business became a fast-growing part of Walmartâs overall operations. In leading Walmartâs expansion into mature and emerging markets, Mike built an international management team that delivered strong operational results in a complex global environment.\r\n\r\nPrior to joining the company, Mike had 23 years of experience in retailing with Federated Department Stores and May Department Stores.\r\n\r\nMike serves on the board of directors of Wal-Mart Stores, Inc., the board of directors of The Consumer Goods Forum, the executive committee of Business Roundtable and is on the executive board of Conservation International\'s Center for Environment Leadership in Business. He also serves on the board of advisors for the University of Arkansas and the advisory board of the Tsinghua University School of Economics and Management in Beijing, China. He is a member of the National Academy of Engineering.\r\n\r\nMike graduated from Georgia Tech with a bachelorâs degree in industrial engineering. He and his wife, Susan, have two daughters and a son.',
    start_date: '1949-12-07',
    end_date: '',
    website: '',
    is_current: '1',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2014-07-24 15:45:35',
    uri: 'http://littlesis.org/person/1016/Michael_T_Duke',
    api_uri: 'http://api.littlesis.org/entity/1016.xml' },
  { id: '92138',
    name: 'Ed Chan',
    description: 'President, CEO - Walmart China',
    summary: 'Ed Chan joined Walmart in 2006 & become President and CEO of Walmart China in February 2007. He is responsible for the companyâs China retail operation and chair the global Zero Waste efforts in the company.\r\n\r\nIn August 2010, Ed Chan was listed as one of The Top 10 People Making Outstanding Contribution to the Investment in Hunan Province and the Top 10 MNC Leaders Influencing Shenzhen SEZâs development during the past 30 years. In March 2009, Ed Chan was awarded as âone of the top 25 people who helped internationalize Chinese commerce in 2008â; In November 2008, named â2008 CCFA Retail Industry People of The Yearâ by CCFA; In August, 2008, awarded "the Most Social Responsible Entrepreneurâ by Manpower Resources and PKU Business Review with Walmart China being awarded â2008 Best Employerâ.\r\n\r\nEd Chan is a corporate leader in sustainable growth in China and was reported by Forbes China in a cover story as he was named among the dozen outstanding âPeople of the Year 2009â as the âLow-Carbon Economy Person of the Yearâ in December 2009, and was named the âPerson for Green Contributionâ by Guanghua Green Harmony Fund and Club 100 in January, 2010.\r\n\r\nUnder Mr. Chanâs leadership, Walmart China has been ranked number one on the annual listing of multinational companies making contributions to China, received â2009 Best Corporate Public Image Awardâ, and was listed as one of â The Top 10 Global Leaders in Green Economyâ & â2010 Hurun CSR Top 50â. The Walmart brand was on the list of âThe top 100 brands in Chinaâ, and the list of âThe top 10 foreign brandsâ, and was awarded âThe Leading Brand of Low-carbonâ and âThe Top Charity Brand that Influences Chinaâ.\r\n\r\nBefore joining Walmart, Chan was Regional Director North Asia of the Dairy Farm Group and a Director of Dairy Farm Management Services Limited. He was responsible for the Groupâs retail businesses in Chinaâs mainland, Hong Kong, Taiwan and Korea. He was in that position since November 2001. Prior to that, he was the Chief Executive Officer of the Groupâs Wellcome Supermarket Division in Taiwan.\r\n\r\nPrior to Dairy Farm, Chan worked for Bertelsmann Music Group (BMG), a unit of Bertelsmann AG, starting in 1989 as corporate development manager based in New York. He was later named Managing Director of BMG Taiwan and was subsequently promoted to Managing Director of BMG Hong Kong and China.\r\n\r\nChan began his professional career as an analyst with McKinsey & Company in San Francisco and Hong Kong for two years. He holds a Bachelor degree from the University of Chicago and a Master Degree from the Sloan School of Management, Massachusetts Institute of Technology.',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2014-02-17 10:30:02',
    uri: 'http://littlesis.org/person/92138/Ed_Chan',
    api_uri: 'http://api.littlesis.org/entity/92138.xml' },
  { id: '33550',
    name: 'Sylvia Mathews Burwell',
    description: 'Secretary, Health and Human Services | former president of the Walmart Foundation',
    summary: 'Sylvia Mathews Burwell is president of the Walmart Foundation, where she leads the company\'s charitable giving efforts and Walmart\'s Global Women\'s Economic Empowerment Initiative. Ms. Burwell also guides the company\'s social, environmental, and economic opportunity efforts in Africa. Prior to joining Walmart, Ms. Burwell was president of the global development program at the Bill and Melinda Gates Foundation, where she led a variety of initiatives including grantmaking and advocacy in agricultural development; financial services for the poor; and water, sanitation, and hygiene. Before joining the Bill and Melinda Gates foundation, Ms. Burwell served in the Clinton administration as deputy director of the Office of Management and Budget, deputy chief of staff to the president, and chief of staff to Secretary of the Treasury Robert E. Rubin. She is based in Bentonville, AR.',
    start_date: '1965-00-00',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2015-03-26 23:29:24',
    uri: 'http://littlesis.org/person/33550/Sylvia_Mathews_Burwell',
    api_uri: 'http://api.littlesis.org/entity/33550.xml' },
  { id: '43964',
    name: 'Raul Vazquez',
    description: 'CEO, Walmart.com',
    summary: 'As President and CEO of Walmart.com, Raul Vazquez oversees the online development and operations of the worldâs largest retailer. He was promoted to this position in early 2007.\r\nPreviously, Mr. Vazquez served as the chief marketing officer of Walmart.com, and was responsible for all consumer marketing and customer-facing sitefunctionality. He managed teams across a variety of\r\nmarketing and creative functions including online, email and in-store marketing, consumer insights, category and brand marketing, corporate communications, editorial, design, imagery and information architecture.\r\nPrior to joining Walmart.com, Mr. Vazquez spent four years at startup companies such as Ventro and Onsale.Before that time, he spent several years at a boutique consulting firm that specializes in competitive strategy\r\nfor Fortune 100 firms, and as an industrial engineer at Baxter Healthcare.\r\n\r\nMr. Vazquez is a graduate of the Wharton Business School, University of Pennsylvania, and also received a bachelorâs and masterâs degree in industrial engineering from Stanford University.',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '1',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2012-02-23 16:48:19',
    uri: 'http://littlesis.org/person/43964/Raul_Vazquez',
    api_uri: 'http://api.littlesis.org/entity/43964.xml' },
  { id: '96401',
    name: 'Mitchell Goldhar',
    description: 'Canadian real estate billionaire',
    summary: 'Legend has it in his native Toronto that SmartCentres President and CEO Mitchell Goldhar paid an unsolicited visit to Sam Walton in the early 1990s, refusing to leave the prolific retailer\'s Arkansas office until the older man agreed to name Goldhar his exclusive developer in Canada. Though Walton declined, Goldhar\'s tenacity had impressed Walton enough to give him a shot. The rest is history as Goldhar soon became Walmart\'s de facto exclusive developer in the country, literally paving the way for Walmart as it moved into the market. Goldhar is still developing his Walmart-anchored SmartCentres, many of which he then sells to Calloway, a real estate investment trust in which he holds a 22% stake. He manages the parallel operations out of SmartCentres headquarters, known as "the Igloo," in Vaughn, Ontario.',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2015-03-09 16:47:47',
    uri: 'http://littlesis.org/person/96401/Mitchell_Goldhar',
    api_uri: 'http://api.littlesis.org/entity/96401.xml' },
  { id: '184430',
    name: 'Stephanie Yazgi',
    description: 'Political Operative',
    summary: 'Stephanie Yazgi is an experienced community organizer, political strategist, and coalition-builder with a track record of winning issue and electoral campaigns. At her previous job with the Center for Popular Democracy, she focused on capacity building, campaign development, and strategic organizing initiatives on a variety of issues. She uses her experience in the field and to craft trainings and curricula for use by campaigns and membership based organizations across the country. Before that, she was the Campaign Director for Walmart Free NYC, a groundbreaking campaign, part of the UFCW International Unionâs Making Change at Walmart network, that defeated Walmartâs multi-million dollar effort to enter New York City. Prior to that, Stephanie worked as a senior operative for the New York State Senate Democratic Conference managing a statewide operation to promote progressive legislation through issue organizing campaigns and constituency mobilization. Through her work with the NYS-DSCC, she managed electoral campaigns, with a focus in strong field operations, to elect Democrats to that house which tipped the balance of power in their favor for the first time in 43 years. She attended Boston University where she majored in Sociology, then went on to Columbia University School of Social work where she obtained her M.S.S.W. Over the years, she has authored and facilitated a number of trainings on community, political and electoral organizing and is an adjunct professor of social work at Hunter College and NYU.',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2015-02-22 16:56:23',
    uri: 'http://littlesis.org/person/184430/Stephanie_Yazgi',
    api_uri: 'http://api.littlesis.org/entity/184430.xml' },
  { id: '67826',
    name: 'Jesse H Ruiz',
    description: 'Partner, Drinker Biddle & Reath',
    summary: 'Jesse H. Ruiz is a partner in the firm\'s Corporate and Securities Group, serves as the firm\'s Marketing Partner, and is a member of the firmâs Client Service Committee.  For over 16 years, Jesse has focused his practice on business transactions, including mergers and acquisitions, venture capital and private equity investments, equity and debt offerings, financings, the purchase and sale of assets from bankruptcy estates and a variety of commercial transactions.  Drawing on his experiences in business and management consulting, and his work in the public sector, Jesse also counsels public and privately-held companies and entrepreneurs on strategic initiatives and transactions.  Jesse also counsels clients on corporate finance issues; negotiation of consulting and other commercial agreements; reorganizations; corporate compliance; corporate governance issues; employment matters; and the formation of business entities in the United States, Latin America and Europe. \r\n\r\nAdditionally, Jesse serves as the relationship partner for a major firm client and supervises and manages all aspects of the firmâs legal services, including those in contract, corporate, compliance, customs & trade, environmental, labor & employment, intellectual property, land use & zoning, litigation, real estate and regulatory matters.\r\n\r\nIn 2011, the Walmart Legal Department awarded Jesse its inaugural Walmart Legal Spark Award for âoutstanding client and community service and dedication to diversity in the legal profession."\r\n\r\nSince 2006, Jesse has served as a member of the board of directors of Commonwealth Edison, an Exelon Company.\r\n\r\nAcquisitions and Divestitures. Jesse has represented public and private acquirers and sellers, and employee stock ownership plan (ESOP) trustees, in a range of transactions across a variety of industries, including public utilities, manufacturing, technology, publishing, financial and consulting.\r\n\r\nJesse has also served as lead counsel in a number of international transactions, including counseling a Canadian client on the leveraged buyout of a dedicated Web hosting business in the United States; serving as U.S. counsel to an Indian company in the sale of its Mumbai-based market research business to a British buyer in London; and representing an Australian company in the sale of one of its subsidiaries, one of North Americaâs largest welded tube companies, to one of the largest integrated steel producers in the United States.\r\n\r\nOther representative transactions include: \r\n\r\nThe $1.4 billion merger of a public utility holding company with another public utility holding company.  The transaction involved numerous state and federal regulatory issues and filings.\r\nSale of an agricultural equipment manufacturing business to a public company.\r\nPurchase of an information technology consulting assets from the bankruptcy estate of another consulting firm.\r\nRepresenting an Employee Stock Ownership Plan and Trust in its purchase of all the outstanding stock of a food and beverage distribution company.\r\nRepresenting the shareholders of an investment company in the sale of all their shares to a bank holding company.\r\nSale of an Australian-owned mining equipment manufacturing business to a U.S. buyer.\r\nThe sale of all the assets of a consulting industry publishing company, and producer of tradeshows, to a large national publishing company.\r\nThe acquisition of an intermodal transportation business by a private equity fund.\r\nLegislative Legal Counsel. Jesse is legal counsel to the fourteen Illinois senators and representatives who formed the Illinois Legislative Latino Caucus and the Illinois Legislative Latino Caucus Foundation.  In 2003, and again in 2009, he received the Foundationâs Leadership Award for providing legal counsel to both the Foundation and the Caucus, and assisting in the formation of both organizations.\r\n\r\nEducation Advocacy. In May 2011, Chicago Mayor Rahm Emanuel appointed Jesse the Vice President of the Chicago Board of Education. The Board oversees the operations of the Chicago Public Schools, the third largest school district in the nation, with approximately 400,000 students and a budget exceeding $5 billion.\r\n\r\nU.S. Secretary of Education Arne Duncan appointed Jesse to the U.S. Department of Education Equity and Excellence Commission in February 2011.\r\n\r\nThe two appointments are the latest in a career of involvement in public education for Jesse.\r\n\r\nPrior to accepting the Mayorâs appointment to the Chicago Board of Education, Jesse served as chairman of the Illinois State Board of Education from September 2004 to May 2011. The Illinois State Board of Education oversees the operation of the stateâs school system for 2.1 million students in grades Pre-K-12, and administers an $11 billion annual budget.  He had also previously served on the Chicago Public Schools Desegregation Monitoring Commission.\r\n\r\nCommunity and Other Activities. In August 2013, Jesse was appointed by the president of the ABA to the Commission on Hispanic Legal Rights and Responsibilities, an historic commission that aims to ensure that the voices of the Latino community across this nation are heard.\r\n\r\nHe is past president of the Hispanic Lawyers Association of Illinois and Past Chairman of the Hispanic Lawyers Scholarship Fund of Illinois.  He is also Past Chairman of the Chicago Committee on Minorities in Large Law Firms.  He has taught corporate law as an Adjunct Professor of Corporate Law at John Marshall Law School. He also serves on several other civic and charitable boards and committees.\r\n\r\nAwards and Honors. In April 2012, Jesse, along with his wife, received the Barristers Philanthropic Award from Lawyers Lend-A-Hand to Youth for his work in education advocacy and youth mentoring.\r\n\r\nIn March 2007, El Valor, one of the countryâs leading nonprofits serving the Hispanic Community, awarded Jesse their Education Excellence Award for his work to open doors for educational opportunities for everyone.\r\n\r\nIn September 2005, he was selected by Illinois Secretary of State Jesse White to receive his Education Award, honoring his commitment to promoting leadership in the Hispanic community and the City of Chicago and as an individual who contributes to improving the quality of life of all Latinos in Illinois.\r\n\r\nHe also received the Chicago Bar Associationâs 2005 Vanguard Award as a Chicago-area lawyer who has âmade the law and legal profession more accessible to, and reflective of, the community at-large.â\r\n\r\nIn 2003, Jesse was also profiled in the prestigious Crainâs Chicago Business list of â40 Under 40 Rising Stars in Chicago Business.â  That same year, he was recognized by Chicago Lawyer magazine as one of the â40 Attorneys Under 40 in Illinois to Watchâ and was selected by Chicago United to be featured in its first âBusiness Leaders of Colorâ publication, featured in the October 13, 2003 issue of Crainâs Chicago Business.\r\n\r\nIn General. Prior to joining the firm, Jesse was a management consultant with the international consulting firm of Booz Allen & Hamilton, Inc. (n/k/a Booz & Company), where he was a member of the Operations Management Group.  At Booz Allen, Jesse assisted clients with developing a profitability roadmap, redesigning a nation-wide customer service system, and implementing a lean manufacturing initiative.  Prior to attending law school, he was also a member of the sales departments of Inland Steel Company and Ryerson Coil Processing Company.  In addition to his industrial sales duties at Ryerson, Jesse participated in an employee team that successfully re-engineered the companyâs operations and brought it to sustained profitability.\r\n\r\nJesse received his J.D. from The University of Chicago Law School, where he served as an editor of the University of Chicago Law School Roundtable, and his Bachelor of Arts degree in economics from the University of Illinois at Urbana-Champaign.',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2014-11-28 00:23:26',
    uri: 'http://littlesis.org/person/67826/Jesse_H_Ruiz',
    api_uri: 'http://api.littlesis.org/entity/67826.xml' },
  { id: '94382',
    name: 'Michael S Moore',
    description: 'President, Walmart Central, Walmart U.S.',
    summary: '',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2014-05-09 22:29:02',
    uri: 'http://littlesis.org/person/94382/Michael_S_Moore',
    api_uri: 'http://api.littlesis.org/entity/94382.xml' },
  { id: '153482',
    name: 'Michael J Bender',
    description: 'President, Walmart West, Walmart U.S.',
    summary: '',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2014-05-09 22:31:02',
    uri: 'http://littlesis.org/person/153482/Michael_J_Bender',
    api_uri: 'http://api.littlesis.org/entity/153482.xml' },
  { id: '153487',
    name: 'Pamela K Kohn',
    description: 'Executive Vice President and President, Walmart Realty, Walmart U.S.',
    summary: '',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2014-05-09 22:33:01',
    uri: 'http://littlesis.org/person/153487/Pamela_K_Kohn',
    api_uri: 'http://api.littlesis.org/entity/153487.xml' },
  { id: '153494',
    name: 'JoaquÃ­n GonzÃ¡lez Varela',
    description: 'President, Walmart East, Walmart U.S.',
    summary: '',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2014-05-09 22:19:13',
    uri: 'http://littlesis.org/person/153494/JoaquÃ­n_GonzÃ¡lez_Varela',
    api_uri: 'http://api.littlesis.org/entity/153494.xml' },
  { id: '1009',
    name: 'Gregory Boyd Penner',
    description: 'General Partner at Madrone Capital Partners; grandson-in-law of Sam Walton',
    summary: 'Mr. Penner has been a General Partner at Madrone Capital Partners, an investment management firm, since 2005. From 2002 to 2005, he served as Wal-Mart\'s Senior Vice President and Chief Financial Officer - Japan. Prior to working for Wal-Mart, Mr. Penner was a General Partner at Peninsula Capital, an early stage venture capital fund, and a financial analyst for Goldman, Sachs & Co. Mr. Penner is a member of the board of directors of Baidu.com, Inc., 99Bill Corporation, Cuill Inc., and Global Hyatt Corporation. \r\n\r\nPenner received his MBA from Stanford University in 1997 before taking a series of Wal-Mart management jobs. In 2005, he started Madrone Capital Partners, a firm backed by money from Wal-Mart Chairman Rob Walton and other family members. Penner then joined Wal-Martâs board in 2008.\r\n\r\nPenner is the son of Clifford and Joyce Penner, two sex therapists in Pasadena, California, who have written numerous books. He joined the billionaire Wal-Mart family by marrying Carrie Walton Penner, the granddaughter of Sam Walton, who died in 1992. The couple both attended Georgetown University as undergraduate students and went on to earn graduate degrees at Stanford. The Penners have four kids and live in the wooded Silicon Valley suburb of Atherton.\r\n\r\nBefore founding Madrone, he was chief financial officer of Wal-Mart Japan and the senior vice president of finance and strategy for Walmart.com. He also served as a general partner at Peninsula Capital, an early-stage venture firm, and worked as a financial analyst at Goldman Sachs Group Inc. early in his career. He first worked for Wal-Mart in 1994 as a manager trainee and an assistant buyer.\r\n\r\nPenner and his wife have ties to the charter-school movement. Carrie Penner serves on boards for Alliance for School Choice, the California Charter Schools Association, and of the KIPP Foundation, a national public charter school network. Greg Penner is a director for the Charter School Growth Fund and Teach for Americaâs national board. The Walton Family Foundation, the familyâs charitable arm, has donated more than $300 million to charter schools since 1997.\r\n\r\nPenner is a partner in DT Capital Partners, a China-based venture firm that focuses on investments in consumer, media, energy and technology sectors.',
    start_date: '1970-00-00',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2014-06-07 15:36:12',
    uri: 'http://littlesis.org/person/1009/Gregory_Boyd_Penner',
    api_uri: 'http://api.littlesis.org/entity/1009.xml' },
  { id: '2554',
    name: 'Jeanne P Jackson',
    description: '',
    summary: 'Jeanne P. Jackson Ms. Jackson is the General Partner of MSP Capital, a consulting and investment firm she founded in 2003. Ms. Jackson was Chief Executive Officer of Walmart. com from March 2000 to January 2002. Ms. Jackson joined McDonald\'s Board in 1999 and is a member of the class of 2009. She also serves on the boards of NIKE, Inc. and Nordstrom, Inc.',
    start_date: '1952-00-00',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2013-11-18 14:44:59',
    uri: 'http://littlesis.org/person/2554/Jeanne_P_Jackson',
    api_uri: 'http://api.littlesis.org/entity/2554.xml' },
  { id: '3205',
    name: 'Margaret A McKenna',
    description: 'Former President, Walmart Foundation',
    summary: 'MARGARET A. McKENNA president, The Wal-Mart Foundation and former president, Lesley University. She received her undergraduate degree from Emmanuel College and her law degree from Southern Methodist University. Ms. McKenna was a civil rights attorney with the U.S. Department of Justice and held a variety of positions with the U.S. government from 1976 to 1981, including deputy counsel in the White House and deputy under secretary of education.',
    start_date: '1946-00-00',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2015-03-27 00:18:55',
    uri: 'http://littlesis.org/person/3205/Margaret_A_McKenna',
    api_uri: 'http://api.littlesis.org/entity/3205.xml' },
  { id: '6063',
    name: 'Rosalind G Brewer',
    description: 'SVP, Division President - Walmart',
    summary: 'Director of Molson Coors since February 2006. Ms. Brewer has been Senior Vice President and Division President of Operations and Regional General Manager of Wal-Mart Stores, Inc. since 2006. From 2004 to 2006, she served as President of Global Nonwovens division of Kimberly-Clark Corporation. Ms. Brewer had been with Kimberly-Clark since 1984, and held a variety of leadership positions across multiple businesses spanning technology and business aspects of the company. Ms. Brewer is immediate past president of Georgia\'s non-profit Board of Directors Network, and serves on several other non-profit boards. She holds a B.S. in Chemistry from Spelman College, and has been a trustee of Spelman College since 2006.',
    start_date: '1963-00-00',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2014-09-25 00:29:20',
    uri: 'http://littlesis.org/person/6063/Rosalind_G_Brewer',
    api_uri: 'http://api.littlesis.org/entity/6063.xml' },
  { id: '33448',
    name: 'Ann Walker Marchant',
    description: 'D.C. socialite and niece of Vernon Jordan',
    summary: 'Ann Walker Marchant is the founder and CEO of the Walker Marchant Group (WMG) - a public relations firm specializing in corporate communications, litigation communications, issues management and media planning. With a core client base across industry lines, WMG provides strategic and targeted solutions to corporate brand challenges. \r\n\r\nWMG provides senior-level strategic communications counsel to some of the world\'s premier corporate brands, such as Eli Lilly and Company, Best Buy, Arbitron, Walmart, Walgreens, Johnson & Johnson and Toyota. The firm develops strategic partnerships that support issues impacting target audiences. \r\n\r\nPrior to founding WMG, Ann was Executive Vice President and Director of Global Business Development at Weber Shandwick International â an Interpublic Group of Companies (IPG). She led the corporate practice and oversaw global integrated advertising and public relations campaigns. \r\n\r\nAnn spent six years in the White House where she served as Special Assistant to the President and Director of Research and Special Projects for Communications for President Clinton. She was responsible for developing and implementing communications strategy in support of key Presidential initiatives. In addition to major policy programs, she managed communications on projects requiring legislative support, public support and editorial support. Ann managed the rapid response operation on key legislative efforts. \r\n\r\nAnn was a partner and senior public relations director for ImagiNations S.A. in Paris, an international consulting firm. \r\n\r\nAnn began her career in communications at Burson Marsteller in New York and later went to Hill and Knowlton where she specialized in corporate and crisis communications. \r\n\r\nShe serves as a director on the boards of Africare, the Howard University Board of Visitors for the John H. Johnson School of Communications and Knock Out Abuse Against Women. She attended Sarah Lawrence College, and resides in Washington, D.C. with her daughter.',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2014-06-21 17:52:41',
    uri: 'http://littlesis.org/person/33448/Ann_Walker_Marchant',
    api_uri: 'http://api.littlesis.org/entity/33448.xml' },
  { id: '35771',
    name: 'Donald S Perkins',
    description: 'Retired Chairman, Jewel Companies, Inc.',
    summary: 'Donald Perkins, a retired grocery executive and the first chairman of the Civic Committee of the Commercial Club of Chicago, died March 25 2015 at his Northfield home, according to Smith-Corcoran Funeral Home. He was 88.\r\n\r\nPerkins was CEO of Jewel from 1970 to 1980 before the grocery chain surrendered its independence to a succession of out-of-town corporate owners, first with American Stores in 1984. Though battered by new entrants, including Whole Foods, Walmart and Mariano\'s, in a changing grocery landscape, Jewel outflanked its local rival, Dominick\'s, which closed in 2013.\r\n\r\nBorn in St. Louis and a graduate of Yale University, with an MBA from Harvard Business School, Perkins was a Civic Committee founder and helped direct its first project, a 1984 study, "Jobs for Metropolitan Chicago."\r\n\r\nHe also was a prolific independent director of various companies, including AT&T, Aon, Corning, Cummins Engine, Firestone, Inland Steel, Kmart, Kodak, AT&T, G.D. Searle and Time Warner.',
    start_date: '1927-00-00',
    end_date: '2015-03-25',
    website: '',
    is_current: '',
    primary_type: 'Person',
    parent_id: '',
    updated_at: '2015-03-28 15:22:16',
    uri: 'http://littlesis.org/person/35771/Donald_S_Perkins',
    api_uri: 'http://api.littlesis.org/entity/35771.xml' }
  ],
  getAdjacentEntitiesResult: [
  { id: '20',
    name: 'Goldman Sachs',
    description: 'Bank holding company',
    summary: '',
    start_date: '1869-00-00',
    end_date: '',
    website: 'http://www.gs.com',
    is_current: '1',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2015-05-18 18:58:38',
    uri: 'http://littlesis.org/org/20/Goldman_Sachs',
    api_uri: 'http://api.littlesis.org/entity/20.xml',
    degree1_num: '3',
    degree1_ids: '1026,1353,1018' },
  { id: '133480',
    name: 'The Cooper Institute',
    description: 'Founded by Kenneth H. Cooper, M.D., M.P.H., the âFather of Aerobics,â',
    summary: 'The Cooper Institute (CI), established in 1970, is a 501.c.3. nonprofit research and education organization dedicated globally to preventive medicine. The Instituteâs founder, Kenneth H. Cooper, M.D., M.P.H., the âFather of Aerobics,â was an Air Force physician who became interested in the role of exercise in preserving health. When he published his first best seller, Aerobics, in 1968, he introduced a new word and was the spark for millions to become active.\r\n\r\nThe Cooper Instituteâs work is diverse and focuses on advancing preventive health practices for children and adults. Our scientific and education assets serve as the foundation for all we do.',
    start_date: '1970-00-00',
    end_date: '',
    website: 'http://www.cooperinstitute.org/about',
    is_current: '1',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2013-10-03 23:20:25',
    uri: 'http://littlesis.org/org/133480/The_Cooper_Institute',
    api_uri: 'http://api.littlesis.org/entity/133480.xml',
    degree1_num: '3',
    degree1_ids: '1015,1033,15315' },
  { id: '14',
    name: 'Hewlett-Packard',
    description: 'Computer and home electronics manufacturer',
    summary: '',
    start_date: '',
    end_date: '',
    website: 'http://www.hp.com',
    is_current: '',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2015-04-30 00:51:37',
    uri: 'http://littlesis.org/org/14/Hewlett-Packard',
    api_uri: 'http://api.littlesis.org/entity/14.xml',
    degree1_num: '2',
    degree1_ids: '40924,40923' },
  { id: '34',
    name: 'Dell Inc',
    description: '',
    summary: '',
    start_date: '',
    end_date: '',
    website: 'http://www.dell.com',
    is_current: '',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2015-04-15 20:32:21',
    uri: 'http://littlesis.org/org/34/Dell_Inc',
    api_uri: 'http://api.littlesis.org/entity/34.xml',
    degree1_num: '2',
    degree1_ids: '40924,1010' },
  { id: '72',
    name: 'Cisco Systems, Inc.',
    description: 'Internet solutions company that provides hardware, software and services to indiciduals and businesses',
    summary: 'Cisco Systems, Inc. is the worldwide leader in networking for the Internet. Today, networks are an essential part of business, education, government and home communications, and Cisco Internet Protocol-based (IP) networking solutions are the foundation of these networks.\r\n\r\nCisco hardware, software, and service offerings are used to create Internet solutions that allow individuals, companies, and countries to increase productivity, improve customer satisfaction and strengthen competitive advantage. The Cisco name has become synonymous with the Internet, as well as with the productivity improvements that Internet business solutions provide. At Cisco, our vision is to change the way people work, live, play and learn.',
    start_date: '1984-12-10',
    end_date: '',
    website: 'http://www.cisco.com',
    is_current: '1',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2015-05-18 18:34:10',
    uri: 'http://littlesis.org/org/72/Cisco_Systems,_Inc.',
    api_uri: 'http://api.littlesis.org/entity/72.xml',
    degree1_num: '2',
    degree1_ids: '2167,1018' },
  { id: '198',
    name: 'Marriott International, Inc.',
    description: 'Hotel/Lodging company',
    summary: '',
    start_date: '',
    end_date: '',
    website: 'http://www.marriott.com',
    is_current: '',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2015-04-29 01:22:38',
    uri: 'http://littlesis.org/org/198/Marriott_International,_Inc.',
    api_uri: 'http://api.littlesis.org/entity/198.xml',
    degree1_num: '2',
    degree1_ids: '1021,1033' },
  { id: '354',
    name: 'Yahoo! Inc.',
    description: 'Global internet service for consumers and businesses',
    summary: '',
    start_date: '',
    end_date: '',
    website: 'http://www.yahoo.com',
    is_current: '',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2015-04-13 20:55:53',
    uri: 'http://littlesis.org/org/354/Yahoo!_Inc.',
    api_uri: 'http://api.littlesis.org/entity/354.xml',
    degree1_num: '2',
    degree1_ids: '1026,38654' },
  { id: '416',
    name: 'Darden Restaurants',
    description: 'Casual Dining Restaurants',
    summary: '',
    start_date: '',
    end_date: '',
    website: 'http://www.darden.com',
    is_current: '',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2015-03-27 01:49:53',
    uri: 'http://littlesis.org/org/416/Darden_Restaurants',
    api_uri: 'http://api.littlesis.org/entity/416.xml',
    degree1_num: '2',
    degree1_ids: '26174,86849' },
  { id: '17667',
    name: 'KPMG LLP',
    description: 'One of the "Big Four" US accounting firms',
    summary: 'KPMG LLP, the audit, tax and advisory firm, is the U.S. member firm of KPMG International. KPMG Internationalâs member firms have 137,000 professionals, including more than 7,600 partners, in 144 countries.',
    start_date: '',
    end_date: '',
    website: 'http://www.us.kpmg.com/',
    is_current: '1',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2015-04-15 14:50:24',
    uri: 'http://littlesis.org/org/17667/KPMG_LLP',
    api_uri: 'http://api.littlesis.org/entity/17667.xml',
    degree1_num: '2',
    degree1_ids: '34829,2577' },
  { id: '18715',
    name: 'Public Strategies Inc',
    description: 'Gives political advice to business clients',
    summary: '',
    start_date: '',
    end_date: '',
    website: 'http://www.pstrategies.com/',
    is_current: '',
    primary_type: 'Org',
    parent_id: '119014',
    updated_at: '2015-02-04 18:49:39',
    uri: 'http://littlesis.org/org/18715/Public_Strategies_Inc',
    api_uri: 'http://api.littlesis.org/entity/18715.xml',
    degree1_num: '2',
    degree1_ids: '52378,25100' },
  { id: '23785',
    name: 'The Chubb Corporation',
    description: '',
    summary: '',
    start_date: '',
    end_date: '',
    website: 'http://www.chubb.com/',
    is_current: '',
    primary_type: 'Org',
    parent_id: '107647',
    updated_at: '2015-03-27 10:20:54',
    uri: 'http://littlesis.org/org/23785/The_Chubb_Corporation',
    api_uri: 'http://api.littlesis.org/entity/23785.xml',
    degree1_num: '2',
    degree1_ids: '1109,34829' },
  { id: '33342',
    name: 'Harvard Business School',
    description: '',
    summary: '',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Org',
    parent_id: '14730',
    updated_at: '2015-05-18 17:08:59',
    uri: 'http://littlesis.org/org/33342/Harvard_Business_School',
    api_uri: 'http://api.littlesis.org/entity/33342.xml',
    degree1_num: '2',
    degree1_ids: '1109,1010' },
  { id: '33692',
    name: 'Facebook',
    description: 'Online directory and social network',
    summary: 'On February 4th, 2004 Mark Zuckerberg launched The Facebook, a social network that was at the time exclusively for Harvard students. It was a huge hit: in 2 weeks, half of the schools in the Boston area began demanding a Facebook network. Zuckerberg immediately recruited his friends Dustin Moskowitz and Chris Hughes to help build Facebook, and within four months, Facebook added 30 more college networks.',
    start_date: '2004-02-04',
    end_date: '',
    website: 'http://www.facebook.com',
    is_current: '1',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2015-03-27 10:31:25',
    uri: 'http://littlesis.org/org/33692/Facebook',
    api_uri: 'http://api.littlesis.org/entity/33692.xml',
    degree1_num: '2',
    degree1_ids: '1010,72454' },
  { id: '41403',
    name: 'Morehouse College',
    description: 'All-male historically black college in Atlanta',
    summary: '',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2015-01-03 15:31:51',
    uri: 'http://littlesis.org/org/41403/Morehouse_College',
    api_uri: 'http://api.littlesis.org/entity/41403.xml',
    degree1_num: '2',
    degree1_ids: '86849,1016' },
  { id: '42104',
    name: 'SFMOMA',
    description: 'San Francisco Museum of Art, founded in 1935,  the first museum on the West Coast devoted to modern and contemporary art.',
    summary: 'As part of the San Francisco Museum of Modern Art (SFMOMA)âs expansion project, the museum has gone beyond its walls and directly into the community with extensive off-site programming while its building is temporarily closed for construction from June 3, 2013, to early 2016.\r\n\r\nSince SFMOMAâs founding in 1935, the museum has drawn nearly 23 million visitors, 50 percent of them since moving to its current location on Third Street in 1995. Over the past 17 years, San Franciscoâs South of Market neighborhood has grown up around the museum: new hotels, retail, restaurants, and residential properties were built and continue to thrive, all contributing to the tax base and economic vitality of the city. In 2016, SFMOMAâs new home will again transform the neighborhood as a major tourist attraction and as an employer: upon completion of the expansion, SFMOMA anticipates an over 20 percent increase in number of employees, as well as a 20 percent growth in its audiences, which averaged 650,000 annually in the years leading up to the museumâs temporary building closure for construction. The expansion will create more than 1,400 new jobs in construction and related areas, and SFMOMA will be an even greater economic stimulant when it expands its operations and purchases of goods and services from Bay Area businesses.\r\n\r\nTo date, SFMOMA has raised more than $570 million toward its $610 million capital campaign goalâa total that includes funds for both construction and endowment.',
    start_date: '1935-00-00',
    end_date: '',
    website: 'http://www.sfmoma.org/pages/about_sfmoma',
    is_current: '1',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2014-12-22 22:57:30',
    uri: 'http://littlesis.org/org/42104/SFMOMA',
    api_uri: 'http://api.littlesis.org/entity/42104.xml',
    degree1_num: '2',
    degree1_ids: '1010,38654' },
  { id: '49186',
    name: 'School of Economics and Management Tsinghua University',
    description: '',
    summary: '',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Org',
    parent_id: '94479',
    updated_at: '2013-03-24 11:52:48',
    uri: 'http://littlesis.org/org/49186/School_of_Economics_and_Management_Tsinghua_University',
    api_uri: 'http://api.littlesis.org/entity/49186.xml',
    degree1_num: '2',
    degree1_ids: '1026,1016' },
  { id: '66860',
    name: 'Walton Family Foundation Inc',
    description: '',
    summary: '',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2014-11-04 03:37:57',
    uri: 'http://littlesis.org/org/66860/Walton_Family_Foundation_Inc',
    api_uri: 'http://api.littlesis.org/entity/66860.xml',
    degree1_num: '2',
    degree1_ids: '1029,1020' },
  { id: '89485',
    name: 'Children\'s Scholarship Fund',
    description: '',
    summary: '',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2014-11-03 06:31:05',
    uri: 'http://littlesis.org/org/89485/Children\'s_Scholarship_Fund',
    api_uri: 'http://api.littlesis.org/entity/89485.xml',
    degree1_num: '2',
    degree1_ids: '1028,1020' },
  { id: '103280',
    name: 'Fix the Debt',
    description: 'organization advocating fiscal austerity',
    summary: '',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Org',
    parent_id: '',
    updated_at: '2014-05-16 16:34:28',
    uri: 'http://littlesis.org/org/103280/Fix_the_Debt',
    api_uri: 'http://api.littlesis.org/entity/103280.xml',
    degree1_num: '2',
    degree1_ids: '1021,2167' },
  { id: '106423',
    name: 'Walmart Stores U.S',
    description: 'Largest division of Walmart Stores, Inc.',
    summary: '',
    start_date: '',
    end_date: '',
    website: '',
    is_current: '',
    primary_type: 'Org',
    parent_id: '1',
    updated_at: '2013-09-29 12:31:14',
    uri: 'http://littlesis.org/org/106423/Walmart_Stores_U.S',
    api_uri: 'http://api.littlesis.org/entity/106423.xml',
    degree1_num: '2',
    degree1_ids: '1017,86849' }
  ],
  mitchellMap: {
    "entities": [
    {
      "id": 69673,
      "name": "The Cynthia & George Mitchell Foundation",
      "image": "//pai-littlesis.s3.amazonaws.com/assets/netmap-org-68f19aa0cdb4fa3812d2d357e68c1300.png",
      "url": "/org/69673/The_Cynthia_&_George_Mitchell_Foundation",
      "description": null,
      "x": -6.607526529580355,
      "y": -223.4172248840332,
      "fixed": true,
      "type": "Org",
      "hide_image": false,
      "custom": false,
      "scale": 2
    },
    {
      "id": 185772,
      "name": "Nelson H Nease",
      "image": "//pai-littlesis.s3.amazonaws.com/assets/netmap-person-6a12fcec79f5a4db719b619b37b0a204.png",
      "url": "/person/185772/Nelson_H_Nease",
      "description": "Texas attorney and lobbyist",
      "x": 254.9141387939453,
      "y": 1.123593807220459,
      "fixed": true,
      "type": "Person",
      "hide_image": false,
      "custom": false,
      "scale": 1.5
    },
    {
      "id": 79962,
      "name": "America's Natural Gas Alliance",
      "image": "//pai-littlesis.s3.amazonaws.com/assets/netmap-org-68f19aa0cdb4fa3812d2d357e68c1300.png",
      "url": "/org/79962/America's_Natural_Gas_Alliance",
      "description": "Representing North America\u2019s largest independent natural gas exploration and production companies",
      "x": 441.6973876953125,
      "y": 42.88993740081787,
      "fixed": true,
      "type": "Org",
      "hide_image": false,
      "custom": false,
      "scale": 1
    },
    {
      "id": 79148,
      "name": "FTI Consulting, Inc",
      "image": "//pai-littlesis.s3.amazonaws.com/assets/netmap-org-68f19aa0cdb4fa3812d2d357e68c1300.png",
      "url": "/org/79148/FTI_Consulting,_Inc",
      "description": "One of the world\u2019s leading international consulting companies.",
      "x": -253.53692626953125,
      "y": 5.522248268127441,
      "fixed": true,
      "type": "Org",
      "hide_image": false,
      "custom": false,
      "scale": 1.5
    },
    {
      "id": 101171,
      "name": "Energy in Depth",
      "image": "//pai-littlesis.s3.amazonaws.com/assets/netmap-org-68f19aa0cdb4fa3812d2d357e68c1300.png",
      "url": "/org/101171/Energy_in_Depth",
      "description": "IPAA's \"state of the art online resource  center to combat new environmental regulations\"",
      "x": -462.5323791503906,
      "y": 58.69425582885742,
      "fixed": true,
      "type": "Org",
      "hide_image": false,
      "custom": false,
      "scale": 1
    },
    {
      "id": 27725,
      "name": "ViaNovo",
      "image": "//pai-littlesis.s3.amazonaws.com/assets/netmap-org-68f19aa0cdb4fa3812d2d357e68c1300.png",
      "url": "/org/27725/ViaNovo",
      "description": null,
      "x": -168.90985488891602,
      "y": 142.4103546142578,
      "fixed": true,
      "type": "Org",
      "hide_image": false,
      "custom": false,
      "scale": 1.5
    },
    {
      "id": 23370,
      "name": "Brickfield Burchette Ritts & Stone PC",
      "image": "//pai-littlesis.s3.amazonaws.com/assets/netmap-org-68f19aa0cdb4fa3812d2d357e68c1300.png",
      "url": "/org/23370/Brickfield_Burchette_Ritts_&_Stone_PC",
      "description": null,
      "x": 161.12994003295898,
      "y": 144.2220458984375,
      "fixed": true,
      "type": "Org",
      "hide_image": false,
      "custom": false,
      "scale": 1.5
    },
    {
      "id": 263,
      "name": "Apache Corporation",
      "image": "http://s3.amazonaws.com/pai-littlesis/images/profile/aac26358e826816f41545e8d89356678eaa14519_1227028887.png",
      "url": "/org/263/Apache_Corporation",
      "description": null,
      "x": 379.3873291015625,
      "y": 198.1153106689453,
      "fixed": true,
      "type": "Org",
      "hide_image": false,
      "custom": false,
      "scale": 1
    },
    {
      "id": 45975,
      "name": "BP plc",
      "image": "http://s3.amazonaws.com/pai-littlesis/images/profile/e2299610c20e0c87e60daea6e0fdfdb5b989e6ba_1273101704.png",
      "url": "/org/45975/BP_plc",
      "description": "global energy company",
      "x": 271.77671813964844,
      "y": 216.1629867553711,
      "fixed": true,
      "type": "Org",
      "hide_image": false,
      "custom": false,
      "scale": 1
    },
    {
      "id": 222,
      "name": "Devon Energy Corporation",
      "image": "http://s3.amazonaws.com/pai-littlesis/images/profile/bcb14087b32b6bff6d4ba344a3a313093980daf9_1227028821.png",
      "url": "/org/222/Devon_Energy_Corporation",
      "description": "An independent oil and natural gas exploration and production company.",
      "x": -377.139892578125,
      "y": -107.1309585571289,
      "fixed": true,
      "type": "Org",
      "hide_image": false,
      "custom": false,
      "scale": 1
    },
    {
      "id": 192914,
      "name": "Beatty Bangle Strama PC",
      "image": "//pai-littlesis.s3.amazonaws.com/assets/netmap-org-68f19aa0cdb4fa3812d2d357e68c1300.png",
      "url": "/org/192914/Beatty_Bangle_Strama_PC",
      "description": "Texas law firm",
      "x": -2.6333175126352444,
      "y": 116.30101685667205,
      "fixed": true,
      "type": "Org",
      "hide_image": false,
      "custom": false,
      "scale": 1.5
    },
    {
      "id": 192913,
      "name": "Robert L Looney",
      "image": "http://s3.amazonaws.com/pai-littlesis/images/profile/e6d03d51ac98b75ddb72425b52a470f91d24e203_1427735087.png",
      "url": "/person/192913/Robert_L_Looney",
      "description": "Of counsel, Beatty Bangle Strama PC",
      "x": -25.969841760758413,
      "y": 353.0227270617502,
      "fixed": true,
      "type": "Person",
      "hide_image": false,
      "custom": false,
      "scale": 1
    },
    {
      "id": 103518,
      "name": "Texas Oil and Gas Association",
      "image": "//pai-littlesis.s3.amazonaws.com/assets/netmap-org-68f19aa0cdb4fa3812d2d357e68c1300.png",
      "url": "/org/103518/Texas_Oil_and_Gas_Association",
      "description": "Oil and gas industry trade association",
      "x": -306.33580927288915,
      "y": 340.3757315173166,
      "fixed": true,
      "type": "Org",
      "hide_image": false,
      "custom": false,
      "scale": 1
    },
    {
      "id": 2,
      "name": "ExxonMobil",
      "image": "http://s3.amazonaws.com/pai-littlesis/images/profile/ca962ef9bfeb8bcc09375006502c88595849b40f_1227028588.png",
      "url": "/org/2/ExxonMobil",
      "description": "Oil and gas exploration, production, and marketing",
      "x": -409.6171508256235,
      "y": 282.9953909411447,
      "fixed": true,
      "type": "Org",
      "hide_image": false,
      "custom": false,
      "scale": 1
    },
    {
      "id": 437,
      "name": "XTO Energy Inc.",
      "image": "http://s3.amazonaws.com/pai-littlesis/images/profile/84fef21d4eb3005bccaa447ce4eb8aa83dadd7da_1427823853.png",
      "url": "/org/437/XTO_Energy_Inc.",
      "description": "Crude Petroleum and Natural Gas",
      "x": -413.7797484818735,
      "y": 413.96539979124236,
      "fixed": true,
      "type": "Org",
      "hide_image": false,
      "custom": false,
      "scale": 1
    }
  ],
  "rels": [
    {
      "id": "x1",
      "entity1_id": 185772,
      "entity2_id": 69673,
      "category_id": 6,
      "category_ids": [
        6
      ],
      "is_current": 1,
      "is_directional": true,
      "end_date": null,
      "scale": 2,
      "label": "\"Ad hoc advisor\"",
      "url": null,
      "x1": 42.01679992675781,
      "y1": -51.62064743041992,
      "fixed": true,
      "custom": true
    },
    {
      "id": 912693,
      "entity1_id": 185772,
      "entity2_id": 79962,
      "category_id": 6,
      "category_ids": [
        6
      ],
      "is_current": 1,
      "is_directional": true,
      "end_date": null,
      "scale": 1,
      "label": "Lobbyist",
      "url": "/relationship/view/id/912693",
      "x1": null,
      "y1": null,
      "fixed": true,
      "custom": false
    },
    {
      "id": "x2",
      "entity1_id": 79148,
      "entity2_id": 69673,
      "category_id": 6,
      "category_ids": [
        6
      ],
      "is_current": null,
      "is_directional": true,
      "end_date": null,
      "scale": 2,
      "label": "Contractor for natural gas program",
      "url": null,
      "x1": null,
      "y1": null,
      "fixed": true,
      "custom": true
    },
    {
      "id": 912704,
      "entity1_id": 185772,
      "entity2_id": 23370,
      "category_id": 1,
      "category_ids": [
        1
      ],
      "is_current": null,
      "is_directional": true,
      "end_date": null,
      "scale": 1,
      "label": "Attorney",
      "url": "/relationship/view/id/912704",
      "x1": 44.66858673095703,
      "y1": 44.66858673095703,
      "fixed": true,
      "custom": false
    },
    {
      "id": 448831,
      "entity1_id": 263,
      "entity2_id": 79962,
      "category_id": 3,
      "category_ids": [
        3
      ],
      "is_current": 1,
      "is_directional": null,
      "end_date": null,
      "scale": 1,
      "label": "Membership",
      "url": "/relationship/view/id/448831",
      "x1": 34.682647705078125,
      "y1": 30.427261352539062,
      "fixed": true,
      "custom": false
    },
    {
      "id": "x3",
      "entity1_id": 185772,
      "entity2_id": 263,
      "category_id": 6,
      "category_ids": [
        6
      ],
      "is_current": 1,
      "is_directional": 1,
      "end_date": null,
      "scale": 1,
      "label": "Lobbyist",
      "url": null,
      "x1": null,
      "y1": null,
      "fixed": true,
      "custom": true
    },
    {
      "id": "x4",
      "entity1_id": 27725,
      "entity2_id": 263,
      "category_id": 6,
      "category_ids": [
        6
      ],
      "is_current": 1,
      "is_directional": 1,
      "end_date": null,
      "scale": 1,
      "label": "Lobbying firm",
      "url": null,
      "x1": -41.89404916763306,
      "y1": 258.2955017089844,
      "fixed": true,
      "custom": true
    },
    {
      "id": 468826,
      "entity1_id": 45975,
      "entity2_id": 101171,
      "category_id": 5,
      "category_ids": [
        5
      ],
      "is_current": null,
      "is_directional": true,
      "end_date": null,
      "scale": 1,
      "label": "Funder",
      "url": "/relationship/view/id/468826",
      "x1": -127.56698036193848,
      "y1": 296.3818588256836,
      "fixed": true,
      "custom": false
    },
    {
      "id": "x5",
      "entity1_id": 185772,
      "entity2_id": 45975,
      "category_id": 6,
      "category_ids": [
        6
      ],
      "is_current": 1,
      "is_directional": 1,
      "end_date": null,
      "scale": 1,
      "label": "Lobbyist",
      "url": null,
      "x1": null,
      "y1": null,
      "fixed": true,
      "custom": true
    },
    {
      "id": "x6",
      "entity1_id": 23370,
      "entity2_id": 69673,
      "category_id": 6,
      "category_ids": [
        6
      ],
      "is_current": null,
      "is_directional": true,
      "end_date": null,
      "scale": 2,
      "label": "Contractor for natural gas program",
      "url": null,
      "x1": null,
      "y1": null,
      "fixed": true,
      "custom": true
    },
    {
      "id": "x7",
      "entity1_id": 27725,
      "entity2_id": 69673,
      "category_id": 6,
      "category_ids": [
        6
      ],
      "is_current": 1,
      "is_directional": true,
      "end_date": null,
      "scale": 2,
      "label": "Contractor for natural gas program",
      "url": null,
      "x1": null,
      "y1": null,
      "fixed": true,
      "custom": true
    },
    {
      "id": "x8",
      "entity1_id": 79148,
      "entity2_id": 101171,
      "category_id": 10,
      "category_ids": [
        10
      ],
      "is_current": 1,
      "is_directional": 1,
      "end_date": null,
      "scale": 1,
      "label": "Operator",
      "url": null,
      "x1": null,
      "y1": null,
      "fixed": true,
      "custom": true
    },
    {
      "id": 770133,
      "entity1_id": 69673,
      "entity2_id": 222,
      "category_id": 10,
      "category_ids": [
        10
      ],
      "is_current": 1,
      "is_directional": true,
      "end_date": null,
      "scale": 1,
      "label": "$103.6 million in stock",
      "url": "/relationship/view/id/770133",
      "x1": 22.367233276367188,
      "y1": -61.68629455566406,
      "fixed": true,
      "custom": false
    },
    {
      "id": 913500,
      "entity1_id": 79148,
      "entity2_id": 222,
      "category_id": 6,
      "category_ids": [
        6
      ],
      "is_current": 1,
      "is_directional": true,
      "end_date": null,
      "scale": 1,
      "label": "Lobbying firm",
      "url": "/relationship/view/id/913500",
      "x1": null,
      "y1": null,
      "fixed": true,
      "custom": false
    },
    {
      "id": 448838,
      "entity1_id": 222,
      "entity2_id": 79962,
      "category_id": 3,
      "category_ids": [
        3
      ],
      "is_current": 1,
      "is_directional": null,
      "end_date": null,
      "scale": 1,
      "label": "Membership",
      "url": "/relationship/view/id/448838",
      "x1": 74.78227233886719,
      "y1": -475.4355010986328,
      "fixed": true,
      "custom": false
    },
    {
      "id": 929294,
      "entity1_id": 192914,
      "entity2_id": 69673,
      "category_id": 6,
      "category_ids": [
        6
      ],
      "is_current": null,
      "is_directional": false,
      "end_date": null,
      "scale": 2,
      "label": "Contractor for natural gas program",
      "url": "/relationship/view/id/929294",
      "x1": 3.5111427307128906,
      "y1": 7.022285461425781,
      "fixed": true,
      "custom": false
    },
    {
      "id": 929292,
      "entity1_id": 192913,
      "entity2_id": 192914,
      "category_id": 1,
      "category_ids": [
        1
      ],
      "is_current": 1,
      "is_directional": true,
      "end_date": null,
      "scale": 1,
      "label": "Of counsel",
      "url": "/relationship/view/id/929292",
      "x1": null,
      "y1": null,
      "fixed": true,
      "custom": false
    },
    {
      "id": 929480,
      "entity1_id": 222,
      "entity2_id": 103518,
      "category_id": 3,
      "category_ids": [
        3
      ],
      "is_current": 1,
      "is_directional": true,
      "end_date": null,
      "scale": 1,
      "label": "Member",
      "url": "/relationship/view/id/929480",
      "x1": 0,
      "y1": 2.3419189453125,
      "fixed": true,
      "custom": false
    },
    {
      "id": 929293,
      "entity1_id": 192913,
      "entity2_id": 103518,
      "category_id": 1,
      "category_ids": [
        1
      ],
      "is_current": null,
      "is_directional": true,
      "end_date": null,
      "scale": 1,
      "label": "Former President",
      "url": "/relationship/view/id/929293",
      "x1": 16.393447875976562,
      "y1": 55.035125732421875,
      "fixed": true,
      "custom": false
    },
    {
      "id": "x9",
      "entity1_id": 45975,
      "entity2_id": 103518,
      "category_id": 3,
      "category_ids": [
        3
      ],
      "is_current": 1,
      "is_directional": 1,
      "end_date": null,
      "scale": 1,
      "label": "Member",
      "url": null,
      "x1": 69.97804641723633,
      "y1": 264.9954833984375,
      "fixed": true,
      "custom": true
    },
    {
      "id": "x11",
      "entity1_id": 192914,
      "entity2_id": 2,
      "category_id": 6,
      "category_ids": [
        6
      ],
      "is_current": null,
      "is_directional": true,
      "end_date": null,
      "scale": 1,
      "label": "Lobbying firm",
      "url": null,
      "x1": 11.709602355957031,
      "y1": 101.87352752685547,
      "fixed": true,
      "custom": true
    },
    {
      "id": 448858,
      "entity1_id": 437,
      "entity2_id": 79962,
      "category_id": 3,
      "category_ids": [
        3
      ],
      "is_current": 1,
      "is_directional": true,
      "end_date": null,
      "scale": 1,
      "label": "Member",
      "url": "/relationship/view/id/448858",
      "x1": 540.7303276062012,
      "y1": 342.6966247558594,
      "fixed": true,
      "custom": false
    },
    {
      "id": 468824,
      "entity1_id": 437,
      "entity2_id": 101171,
      "category_id": 5,
      "category_ids": [
        5
      ],
      "is_current": null,
      "is_directional": true,
      "end_date": null,
      "scale": 1,
      "label": "Funder",
      "url": "/relationship/view/id/468824",
      "x1": -129.2135009765625,
      "y1": 11.2359619140625,
      "fixed": true,
      "custom": false
    },
    {
      "id": 929475,
      "entity1_id": 437,
      "entity2_id": 103518,
      "category_id": 3,
      "category_ids": [
        3
      ],
      "is_current": 1,
      "is_directional": true,
      "end_date": null,
      "scale": 1,
      "label": "Member",
      "url": "/relationship/view/id/929475",
      "x1": null,
      "y1": null,
      "fixed": true,
      "custom": false
    },
    {
      "id": "x12",
      "entity1_id": 2,
      "entity2_id": 437,
      "category_id": 10,
      "category_ids": [
        10
      ],
      "is_current": 1,
      "is_directional": 1,
      "end_date": null,
      "scale": 1,
      "label": "Subsidiary",
      "url": null,
      "x1": 1.40447998046875,
      "y1": 26.685394287109375,
      "fixed": true,
      "custom": true
    }
  ],
    "texts": []
  }
};
